"""Initialize schemas package."""

from backend.schemas.user import (
    UserCreate,
    UserUpdate,
    UserResponse,
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
)
from backend.schemas.attendance import (
    AttendanceRecordCreate,
    AttendanceRecordResponse,
    AttendanceSessionCreate,
    AttendanceSessionResponse,
    AttendanceSessionPreview,
    AttendanceSummaryResponse,
    StudentAttendanceDetail,
    StudentFullAttendance,
)
from backend.schemas.guidance import (
    SubjectGuidance,
    GuidanceResult,
    GuidanceMessage,
)
from backend.schemas.notification import (
    NotificationCreate,
    NotificationResponse,
    NotificationList,
    NotificationMarkRead,
    BulkNotificationCreate,
)
from backend.schemas.leave import (
    LeaveRequestCreate,
    LeaveRequestPreview,
    LeaveRequestResponse,
    LeaveRequestUpdate,
    LeaveHistory,
)
from backend.schemas.report import (
    AttendanceReportFilter,
    SubjectReportRow,
    SubjectAttendanceReport,
    DepartmentReportSummary,
    WeeklyReportSummary,
    PDFReportRequest,
    ReportDownload,
)
from backend.schemas.agent import (
    AgentStatus,
    AgentAuditLogResponse,
    AgentStatusResponse,
    AllAgentsStatus,
    AgentAuditLogFilter,
    PaginatedAgentLogs,
)
from backend.schemas.subject import (
    DepartmentCreate,
    DepartmentResponse,
    SubjectCreate,
    SubjectResponse,
    SubjectUpdate,
    TimetableCreate,
    TimetableResponse,
    StudentCreate,
    StudentResponse,
    FacultyCreate,
    FacultyResponse,
)

__all__ = [
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "AttendanceRecordCreate",
    "AttendanceRecordResponse",
    "AttendanceSessionCreate",
    "AttendanceSessionResponse",
    "AttendanceSessionPreview",
    "AttendanceSummaryResponse",
    "StudentAttendanceDetail",
    "StudentFullAttendance",
    "SubjectGuidance",
    "GuidanceResult",
    "GuidanceMessage",
    "NotificationCreate",
    "NotificationResponse",
    "NotificationList",
    "NotificationMarkRead",
    "BulkNotificationCreate",
    "LeaveRequestCreate",
    "LeaveRequestPreview",
    "LeaveRequestResponse",
    "LeaveRequestUpdate",
    "LeaveHistory",
    "AttendanceReportFilter",
    "SubjectReportRow",
    "SubjectAttendanceReport",
    "DepartmentReportSummary",
    "WeeklyReportSummary",
    "PDFReportRequest",
    "ReportDownload",
    "AgentStatus",
    "AgentAuditLogResponse",
    "AgentStatusResponse",
    "AllAgentsStatus",
    "AgentAuditLogFilter",
    "PaginatedAgentLogs",
    "DepartmentCreate",
    "DepartmentResponse",
    "SubjectCreate",
    "SubjectResponse",
    "SubjectUpdate",
    "TimetableCreate",
    "TimetableResponse",
    "StudentCreate",
    "StudentResponse",
    "FacultyCreate",
    "FacultyResponse",
]
